version: '3.8'

services:
  in-memory-apis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reckless-bank-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge